name: trips-ci

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
    - 'apis/trips/**'
  pull_request:
    branches: [ main ]
    paths:
    - 'apis/trips/**'

defaults:
  run:
    shell: bash
    working-directory: apis/trips/
    
jobs:
  build:
    name: trips-ci-job
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.13.1' # The Go version to download (if necessary) and use.
    - name: Pre-build
      run: |-
        go mod download github.com/codemodus/swagui
        go get github.com/Azure-Samples/openhack-devops-team/apis/trips/tripsgo
    - name: Build
      run: go build main.go
    # - name: Run the server
    #   run: go run main.go
    - name: Test
      run: go test ./tripgo -run Unit
